# Generated by Django 2.1.8 on 2019-10-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=32, verbose_name='网站名字')),
                ('website_url', models.CharField(max_length=256, verbose_name='网站url')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.User')),
            ],
        ),
    ]
