# Generated by Django 2.1.8 on 2019-10-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'verbose_name_plural': '网站导航'},
        ),
    ]
