# Generated by Django 2.1.8 on 2019-10-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=64, verbose_name='流程名')),
                ('describe', models.CharField(default='', max_length=512, null=True, verbose_name='申请描述')),
                ('attachment', models.CharField(default='', max_length=512, null=True, verbose_name='附件')),
                ('process_str', models.CharField(max_length=256, verbose_name='流程')),
                ('user', models.CharField(default=None, max_length=8, verbose_name='审核人')),
                ('create_time', models.CharField(default='', max_length=128, null=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('0', '审核中'), ('1', '审核拒绝'), ('2', '审核通过')], default='0', max_length=8)),
                ('is_read', models.IntegerField(choices=[(0, '未查看'), (1, '已查看')], default=0, verbose_name='是否查看')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.User')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='流程表名字')),
                ('process', models.CharField(max_length=256, verbose_name='流程')),
                ('describe', models.CharField(max_length=512, verbose_name='描述')),
                ('create_time', models.CharField(max_length=128, verbose_name='创建时间')),
                ('change_time', models.CharField(default='', max_length=128, null=True, verbose_name='修改时间')),
                ('user', models.ManyToManyField(through='process.Intermediate', to='permissions.User')),
            ],
        ),
        migrations.AddField(
            model_name='intermediate',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Process'),
        ),
    ]
