# Generated by Django 2.1.8 on 2019-10-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermediate',
            options={'verbose_name_plural': '流程创建与审核'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': '流程表'},
        ),
    ]
