# Generated by Django 2.1.8 on 2019-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='组名称')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=32, unique=True, verbose_name='服务器名')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='ip地址')),
                ('user', models.CharField(max_length=12, null=True, verbose_name='ssh账号')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='ssh密码')),
                ('port', models.IntegerField(null=True, verbose_name='ssh端口')),
                ('status', models.CharField(choices=[('0', '未认证'), ('1', '已认证')], default='0', max_length=4, verbose_name='状态')),
                ('groups', models.ManyToManyField(blank=True, to='operational.Group', verbose_name='组内的服务器')),
            ],
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='ssh账号')),
                ('password', models.CharField(max_length=32, verbose_name='ssh密码')),
                ('senior', models.IntegerField(choices=[(0, '空'), (1, '有选择')], default=0)),
                ('uid', models.IntegerField(blank=True, null=True, verbose_name='uid')),
                ('gid', models.IntegerField(blank=True, null=True, verbose_name='gid')),
                ('sudo', models.CharField(blank=True, max_length=1024, null=True, verbose_name='sudo权限')),
                ('create_time', models.CharField(max_length=32, null=True, verbose_name='创建时间')),
                ('way', models.IntegerField(choices=[(0, '空'), (1, 'server'), (2, 'group')], default=0)),
                ('groups', models.ManyToManyField(blank=True, to='operational.Group', verbose_name='服务器组')),
                ('servers', models.ManyToManyField(blank=True, to='operational.Server', verbose_name='服务器')),
            ],
        ),
    ]
