# Generated by Django 2.1.8 on 2019-10-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': '服务器组'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': '服务器'},
        ),
        migrations.AlterModelOptions(
            name='serveruser',
            options={'verbose_name_plural': '服务器ssh账号'},
        ),
    ]
