# Generated by Django 2.1.8 on 2019-10-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operational', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_tag', models.CharField(max_length=64, verbose_name='git tag版本')),
                ('git_commit', models.CharField(max_length=256, verbose_name='git commit版本')),
                ('text', models.CharField(max_length=10240, verbose_name='日志文本')),
                ('new_time', models.CharField(max_length=18, verbose_name='操作时间')),
                ('operation_user', models.CharField(max_length=18, verbose_name='操作人')),
                ('on_version_log_id', models.IntegerField(blank=True, null=True, verbose_name='上个版本日志id')),
                ('count_num', models.IntegerField(blank=True, null=True, verbose_name='次数')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='项目名')),
                ('create_time', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='创建时间')),
                ('change_time', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='上次部署时间')),
                ('describe', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='描述')),
                ('git_url', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='git url')),
                ('git_auth_way', models.IntegerField(choices=[(0, '账号密码认证'), (1, '已ssh-key认证')], verbose_name='认证方式')),
                ('git_user', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='git认证账号')),
                ('git_password', models.CharField(blank=True, default='123456', max_length=64, null=True, verbose_name='git认证密码')),
                ('git_branch', models.CharField(default='', max_length=16, verbose_name='分支')),
                ('deploy_dir', models.CharField(max_length=512)),
                ('exclude_file', models.CharField(blank=True, default='', max_length=4096, null=True, verbose_name='排除文件')),
                ('online_notice', models.CharField(choices=[('email', '邮件'), ('dingding', '钉钉')], default='email', max_length=16, verbose_name='通知方式')),
                ('dingding_notice', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='钉钉通知地址')),
                ('work_dir', models.CharField(blank=True, max_length=128, null=True, verbose_name='git clone所在目录')),
                ('connection_auth', models.IntegerField(choices=[(0, '未连接测试'), (1, '连接失败'), (2, '连接成功')], default=0)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.User', verbose_name='创建人')),
                ('email_notice', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role', verbose_name='邮件通知的组')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Log')),
                ('server_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operational.Group', verbose_name='上线服务器组')),
            ],
        ),
    ]
