# Generated by Django 2.1.8 on 2019-10-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name_plural': '项目日志'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目'},
        ),
    ]
