# Generated by Django 2.1.8 on 2019-10-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='组名称')),
            ],
            options={
                'verbose_name_plural': '组',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='菜单')),
            ],
            options={
                'verbose_name_plural': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='权限名')),
                ('url', models.CharField(max_length=64, verbose_name='带正则的url')),
                ('codes', models.CharField(max_length=32, verbose_name='代码')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Group', verbose_name='所属组')),
                ('menu_gp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aaa', to='permissions.Permission', verbose_name='组内菜单')),
            ],
            options={
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='角色')),
                ('permissions', models.ManyToManyField(blank=True, to='permissions.Permission', verbose_name='拥有权限的角色')),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('head_img', models.CharField(default='/static/img/img.jpg', max_length=512, verbose_name='头像')),
                ('create_time', models.CharField(max_length=64, verbose_name='创建时间')),
                ('disable', models.IntegerField(choices=[(0, '启用'), (1, '禁用')], default=0)),
                ('roles', models.ManyToManyField(blank=True, to='permissions.Role')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Menu', verbose_name='组内菜单'),
        ),
    ]
