# Generated by Django 2.1.8 on 2019-10-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.CharField(default='/static/avatar/default_avatar.jpg', max_length=512, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, verbose_name='账号名'),
        ),
    ]
