# Generated by Django 2.1.8 on 2019-10-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20191017_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_img',
            field=models.CharField(default='static/avatar/default_avatar.jpg', max_length=512, verbose_name='头像'),
        ),
    ]
